import type { AppProps } from "next/app";
import MainLayout from "../components/layouts/MainLayout";
import { MantineProvider } from "@mantine/core";
import Head from "next/head";
import { ApolloProvider } from "@apollo/client";
import { useApollo } from "apollo/client";

function MyApp({ Component, pageProps }: AppProps) {
  const apolloClient = useApollo(pageProps);
  return (
    <>
      <Head>
        <title>Rick and Morty</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ApolloProvider client={apolloClient}>
        <MantineProvider
          withGlobalStyles
          withNormalizeCSS
          theme={{
            /** Put your mantine theme override here */
            colorScheme: "dark",
          }}
        >
          <MainLayout>
            <Component {...pageProps} />
          </MainLayout>
        </MantineProvider>
      </ApolloProvider>
    </>
  );
}

export default MyApp;
